on:
  - push
  - pull_request
name: unit tests
jobs:
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod      # Module download cache
            ~/.cache/go-build # Build cache (Linux)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install libsealevel
        run: |
          sudo mkdir -p /usr/local/lib/x86_64-linux-gnu/
          sudo cp -v ./dist/libsealevel.so /usr/local/lib/x86_64-linux-gnu/
          sudo cp -v ./dist/sealevel.h /usr/local/include/
          ldd /usr/local/lib/x86_64-linux-gnu/libsealevel.so
      - name: Test
        run: |
          export LD_LIBRARY_PATH="$(pwd)/dist"
          go test ./... -v
      - name: Check Format
        run: '[ "$(gofmt -l ./ | wc -l)" -eq 0 ]'
